#!/usr/bin/env python
"""
signal_report.py - forward tracker for the WNBA signal board.
Writes FILTER_REPORT.md (renders on GitHub) AND prints to console. Pure stdlib
(no pandas -> safe in cloud + can't hit the WMI import hang). Auto-runs each grade.

Tracks two CANDIDATE filters as the sample grows (NOT yet proven, n is small):
  (1) skip negative odds-CLV bets  -> the price moved against us by the close
  (2) skip big-line (>=18) book-overshoot overs -> the "book trap" big numbers

No wall-clock stamp: the report keys off the data (last date + bet count), so the
file only changes when the underlying bets change -> no noise commits each run.
"""
import csv
import os
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))


def fnum(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return None


def load(name):
    p = os.path.join(HERE, name)
    if not os.path.exists(p):
        return []
    with open(p, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))


def settled(rows):
    out = []
    for r in rows:
        res = (r.get('result') or '').strip().upper()
        if res.startswith('WIN'):
            r['_win'] = 1
            out.append(r)
        elif res in ('LOSS', 'LOSE', 'L'):
            r['_win'] = 0
            out.append(r)
    return out


def rec(items):
    n = len(items)
    w = sum(r['_win'] for r in items)
    pnl = sum(fnum(r['pnl']) or 0 for r in items)
    odds = [fnum(r['odds']) for r in items if fnum(r.get('odds'))]
    be = 100 / (sum(odds) / len(odds)) if odds else 0
    return dict(n=n, w=w, l=n - w, wp=(100 * w / n if n else 0),
                pnl=pnl, upb=(pnl / n if n else 0), be=be)


def is_neg_clv(r):
    v = fnum(r.get('odds_clv'))
    return v is not None and v < -1e-9


def is_big_overshoot(r):
    return r.get('src') == 'overshoot' and (fnum(r.get('line')) or 0) >= 18


def row(label, s):
    return (f"| {label} | {s['n']} | {s['w']}-{s['l']} | {s['wp']:.0f}% | "
            f"{s['pnl']:+.2f}u | {s['upb']:+.3f} |")


g = settled(load('graded_bets.csv'))
out = []
if not g:
    out.append("# WNBA Signal Filter Report\n\n_No settled bets yet._")
else:
    dates = sorted(r['date'] for r in g)
    base = rec(g)
    keep_clv = [r for r in g if not is_neg_clv(r)]
    keep_ovr = [r for r in g if not is_big_overshoot(r)]
    keep_both = [r for r in g if not is_neg_clv(r) and not is_big_overshoot(r)]
    n_neg = sum(1 for r in g if is_neg_clv(r))
    n_big = sum(1 for r in g if is_big_overshoot(r))

    out.append("# WNBA Signal Filter Report")
    out.append(f"_As of {dates[-1]} · {base['n']} settled paper bets ({dates[0]}→{dates[-1]}) · "
               f"flat 1u · auto-generated by `signal_report.py` each grade run._")
    out.append("")
    out.append("## Candidate filters (tracking forward — NOT yet proven)")
    out.append("| view | n | W-L | win% | P&L | u/bet |")
    out.append("|---|--:|:--:|--:|--:|--:|")
    out.append(row("**Baseline** — bet everything", base))
    out.append(row(f"Skip **negative odds-CLV** (−{n_neg} bets)", rec(keep_clv)))
    out.append(row(f"Skip **big book-overshoot overs ≥18** (−{n_big} bets)", rec(keep_ovr)))
    out.append(row("**Both filters**", rec(keep_both)))
    out.append("")
    out.append(f"> Break-even ≈ {base['be']:.0f}% at the board's avg odds. Filters are **directional on a "
               f"small sample (n={base['n']})** — collecting more before acting. Negative-CLV is hindsight "
               f"(known only at close); the live form is *bet late, pass when the price has moved against you*.")
    out.append("")

    # by signal type
    out.append("## By signal type")
    out.append("| signal | n | W-L | win% | P&L | u/bet |")
    out.append("|---|--:|:--:|--:|--:|--:|")
    grp = {}
    for r in g:
        grp.setdefault(r['src'], []).append(r)
    for k in sorted(grp, key=lambda k: rec(grp[k])['pnl'], reverse=True):
        out.append(row(k, rec(grp[k])))
    out.append(row("**TOTAL**", base))
    out.append("")

    # odds-CLV buckets
    out.append("## Odds-CLV buckets (does the line moving our way create winners?)")
    out.append("| bucket | n | W-L | win% | P&L |")
    out.append("|---|--:|:--:|--:|--:|")
    buck = {'beat close (>0)': [], 'flat (0)': [], 'worse close (<0)': [], 'no data': []}
    for r in g:
        v = fnum(r.get('odds_clv'))
        if v is None:
            buck['no data'].append(r)
        elif v > 1e-9:
            buck['beat close (>0)'].append(r)
        elif v < -1e-9:
            buck['worse close (<0)'].append(r)
        else:
            buck['flat (0)'].append(r)
    for k, items in buck.items():
        if items:
            s = rec(items)
            out.append(f"| {k} | {s['n']} | {s['w']}-{s['l']} | {s['wp']:.0f}% | {s['pnl']:+.2f}u |")
    out.append("")

    # overshoot by line size
    ov = [r for r in g if r['src'] == 'overshoot']
    if ov:
        out.append("## Book overshoot — bet the over vs FADE, by line size")
        out.append("| line | n | over W-L | over P&L | fade P&L |")
        out.append("|---|--:|:--:|--:|--:|")
        for lab, t in [("big ≥18", lambda r: (fnum(r['line']) or 0) >= 18),
                       ("small <18", lambda r: (fnum(r['line']) or 0) < 18)]:
            sub = [r for r in ov if t(r)]
            if sub:
                s = rec(sub)
                fade = sum(((fnum(r['odds']) - 1) if r['_win'] == 0 else -1.0) for r in sub)
                out.append(f"| {lab} | {s['n']} | {s['w']}-{s['l']} | {s['pnl']:+.2f}u | {fade:+.2f}u |")
        out.append("")

text = "\n".join(out) + "\n"
with open(os.path.join(HERE, "FILTER_REPORT.md"), "w", encoding="utf-8") as f:
    f.write(text)
print(text)
