import os
D=os.path.dirname(os.path.abspath(__file__))
exec(open(os.path.join(D,"xm_table.py"),encoding="utf-8").read())
print("skips",skip)
print("T rows",len(T))
def c(f): return sum(1 for r in T if f(r))
print("with dline (two-sided anchor)",c(lambda r:r["dline"] is not None))
print("with dline1 (over-only anchor)",c(lambda r:r["dline1"] is not None))
print("with dtot",c(lambda r:r["dtot"] is not None))
print("with dtot & dline1",c(lambda r:r["dtot"] is not None and r["dline1"] is not None))
print("with dspr & dline1",c(lambda r:r["dspr"] is not None and r["dline1"] is not None))
print("markets",collections.Counter(r["mk"] for r in T).most_common())
print("base over rate",round(sum(1 for r in T if r["over_won"])/len(T),4))
print("mean over odds",round(statistics.mean(r["ood"] for r in T),3),"mean under odds",round(statistics.mean(r["uod"] for r in T),3))
print("mean p_over(novig)",round(statistics.mean(r["p_over"] for r in T if r["p_over"]),4))
print("ROI all overs",round(100*statistics.mean(pnl(r,"Over") for r in T),2),"| all unders",round(100*statistics.mean(pnl(r,"Under") for r in T),2))
print("dline1 dist",collections.Counter(r["dline1"] for r in T if r["dline1"] is not None).most_common(9))
print("dtot dist",collections.Counter(r["dtot"] for r in T if r["dtot"] is not None).most_common(12))
print("games covered by pinn in T:",len(set(r["gid"] for r in T if r["dtot"] is not None)))
