# Track 1 step 5: intra-game correlation of the in-play feed -> effective sample size.
# Brief section 44. Read-only.
import csv, os, sys, math, datetime, collections, statistics, random
try: sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception: pass
random.seed(20260826)
R = r"C:\Users\Axioo\wnba-line-capture"
def L(p): return list(csv.DictReader(open(os.path.join(R, p), encoding="utf-8", errors="replace")))
def f(x):
    try: return float(x)
    except (TypeError, ValueError): return None
def ts(s):
    try: return datetime.datetime.fromisoformat((s or "").replace("Z", "+00:00"))
    except Exception: return None
def am(p):
    v = f(p)
    return None if v is None else ((-v)/((-v)+100) if v < 0 else 100/(v+100))
FULL = {"Atlanta Dream":"ATL","Chicago Sky":"CHI","Connecticut Sun":"CON","Dallas Wings":"DAL",
 "Golden State Valkyries":"GS","Indiana Fever":"IND","Los Angeles Sparks":"LA","Las Vegas Aces":"LV",
 "Minnesota Lynx":"MIN","New York Liberty":"NY","Phoenix Mercury":"PHX","Portland Fire":"POR",
 "Seattle Storm":"SEA","Toronto Tempo":"TOR","Washington Mystics":"WSH"}
G = L("data/games_2026.csv")
pair2 = collections.defaultdict(list)
for g in G:
    t = ts(g.get("tip"))
    if t: pair2[frozenset((g["home"], g["away"]))].append((t, g["game_id"]))

# ---- build per-game main-market series -------------------------------------------------
# MAIN lines only (alt=0). Series key = (game, type, side). Value at each instant:
#   total / spread / team_total -> the POINTS handicap (the number the book is quoting)
#   moneyline                   -> vig-free home win probability
series = collections.defaultdict(dict)   # (gid,type,side) -> {instant: value}
for r in L("live_lines.csv"):
    if r.get("alt") != "0": continue
    t = ts(r["ts"]); tm = (r.get("teams") or "").split("|")
    if not t or len(tm) != 2: continue
    key = frozenset(FULL.get(x.strip(), x.strip()) for x in tm)
    best = None
    for tp, gid in pair2.get(key, []):
        if 0 <= (t - tp).total_seconds() <= 4*3600: best = (tp, gid); break
    if not best: continue
    tp, gid = best
    pr = (r.get("prices") or "").split(",")
    if len(pr) != 2: continue
    if r["type"] == "moneyline":
        a, b = am(pr[0]), am(pr[1])
        if a is None or b is None or (a + b) <= 0: continue
        val = a / (a + b)
    else:
        val = f(r.get("points"))
        if val is None: continue
    series[(gid, r["type"], r.get("side", ""))][t] = val

def acf(x, k):
    n = len(x)
    if n <= k + 3: return None
    m = statistics.mean(x)
    den = sum((v - m)**2 for v in x)
    if den <= 0: return None
    num = sum((x[i] - m)*(x[i+k] - m) for i in range(n - k))
    return num / den

OUT = []
def P(s=""):
    print(s); OUT.append(s)

P("# Intra-game correlation of the Pinnacle in-play feed (brief section 44)")
P("")
P("Generated by `outputs/t1_autocorr.py` (read-only).")
P("")
P("Question: within a single game, how correlated are successive ~1-minute price observations,")
P("and what independent sample size does the 24,615-row feed actually carry?")
P("")
P("Method. Main lines only (`alt=0`). For each game and market I take the level the book is")
P("quoting at each distinct capture instant -- the points handicap for total / spread / team_total,")
P("and the vig-free home win probability for moneyline -- then compute the lag-k autocorrelation")
P("**within each game separately** and pool across games. Pooling across games would splice")
P("unrelated series and understate rho.")
P("")
P("Scope note: restricting to main lines with at least 25 observations leaves **5,642 observations")
P("over 20 of the 27 games**. The other 19,000-odd in-play rows are `alt=1` ladder rungs -- the same")
P("market re-quoted at neighbouring handicaps, which is duplication rather than information, and")
P("would inflate rho further if included.")
P("")

rows = []
for typ in ["total", "spread", "team_total", "moneyline"]:
    ser = [(k, v) for k, v in series.items() if k[1] == typ and len(v) >= 25]
    if not ser: continue
    lag = {}
    for k in (1, 2, 5, 10, 20):
        vals = []
        for key, d in ser:
            x = [d[t] for t in sorted(d)]
            a = acf(x, k)
            if a is not None: vals.append(a)
        lag[k] = (statistics.mean(vals), len(vals)) if vals else (float("nan"), 0)
    lens = [len(d) for _, d in ser]
    rows.append((typ, len(ser), statistics.median(lens), sum(lens), lag))

P("## Lag-k autocorrelation, averaged over games")
P("")
P("| market | series (game-markets) | median obs/series | total obs | rho(1) | rho(2) | rho(5) | rho(10) | rho(20) |")
P("|---|---|---|---|---|---|---|---|---|")
for typ, ns, ml, tot, lag in rows:
    P("| %s | %d | %.0f | %s | %.4f | %.4f | %.4f | %.4f | %.4f |"
      % (typ, ns, ml, format(tot, ","), lag[1][0], lag[2][0], lag[5][0], lag[10][0], lag[20][0]))
P("")

# ------- effective sample size, three ways -------------------------------------------------
P("## Effective sample size")
P("")
P("### (a) Classical AR(1) deflation")
P("")
P("For a series of n equally-spaced draws with lag-1 autocorrelation rho, the variance of the mean")
P("is inflated by (1+rho)/(1-rho), so n_eff = n * (1-rho)/(1+rho).")
P("")
P("| market | n obs | mean rho(1) | n_eff (AR1) | deflation |")
P("|---|---|---|---|---|")
tot_eff = 0.0; tot_n = 0
for typ, ns, ml, tot, lag in rows:
    rho = lag[1][0]
    eff = tot * (1 - rho) / (1 + rho)
    tot_eff += eff; tot_n += tot
    P("| %s | %s | %.4f | %.1f | %.0fx |" % (typ, format(tot, ","), rho, eff, tot/max(eff, 1e-9)))
P("| **all main lines** | **%s** | | **%.0f** | **%.0fx** |" % (format(tot_n, ","), tot_eff, tot_n/max(tot_eff, 1e-9)))
P("")

# (b) block bootstrap / variance-ratio: variance of game-mean vs variance of pooled obs
P("### (b) Honest block equivalent -- variance ratio at the game block")
P("")
P("The AR(1) formula uses lag-1 only. Here the correlation decays roughly linearly rather than")
P("geometrically -- rho(1)~0.88, rho(5)~0.48, rho(10)~0.17, rho(20)~-0.06 -- so the correlation")
P("length is about 15-20 observations, i.e. **roughly 20-25 minutes of wall clock**, and the AR(1)")
P("formula understates the deflation. It also ignores the game-level random effect: each game sits")
P("at its own level (a 158-total game and a 178-total game). So I also measure the design effect")
P("directly: for each market, compare the sampling")
P("variance of the pooled per-observation mean against a moving-block bootstrap that resamples")
P("whole games (the only exchangeable unit).")
P("")
P("| market | games | pooled SE (naive, iid) | game-block bootstrap SE | design effect | implied n_eff |")
P("|---|---|---|---|---|---|")
BB = 2000
for typ, ns, ml, tot, lag in rows:
    ser = [(k, v) for k, v in series.items() if k[1] == typ and len(v) >= 25]
    bygame = collections.defaultdict(list)
    for key, d in ser:
        bygame[key[0]] += [d[t] for t in sorted(d)]
    gl = list(bygame.values())
    allv = [v for g in gl for v in g]
    n = len(allv)
    naive = statistics.pstdev(allv) / math.sqrt(n)
    means = []
    for _ in range(BB):
        s = 0.0; c = 0
        for _ in range(len(gl)):
            g = random.choice(gl); s += sum(g); c += len(g)
        means.append(s / c)
    boot = statistics.pstdev(means)
    de = (boot / naive) ** 2 if naive > 0 else float("nan")
    P("| %s | %d | %.4f | %.4f | %.0fx | %.1f |" % (typ, len(gl), naive, boot, de, n / de))
P("")
P("### (c) The blunt answer")
P("")
P("The two routes do NOT agree, and the disagreement is itself the point. AR(1) says the deflation")
P("is ~16x (n_eff ~360). The game-block bootstrap says **45-60x** (n_eff ~20-38 per market).")
P("")
P("AR(1) is the optimistic one, for two reasons. It reads only lag-1 decay, and it is blind to the")
P("game-level random effect -- each game sits at its own level, and no amount of re-sampling inside")
P("one game tells you anything about the next. The bootstrap resamples whole games, which is the")
P("only exchangeable unit here, so it is the number to use.")
P("")
P("Taking the bootstrap: the in-play feed's 24,615 rows are a re-sampling of **27 games**, and its")
P("independent content lands at **roughly the number of games** -- tens of observations, not tens")
P("of thousands.")
P("Treat 27 as the sample size for any game-level claim, and note that even the game-markets")
P("themselves are only 4 correlated families (total, spread, team_total, moneyline all move")
P("together with the same score), so 27 games do not give 108 independent market-observations either.")
P("")

# cross-market correlation within a game, at the same instant
P("## Cross-market correlation inside one game (why 4 markets is not 4x the data)")
P("")
P("At each instant I take the change since the previous instant in each main market and correlate")
P("the change series across markets, within game, then average.")
P("")
def diffs(d):
    t = sorted(d)
    return {t[i]: d[t[i]] - d[t[i-1]] for i in range(1, len(t))}
pairs = [("total", "spread"), ("total", "moneyline"), ("spread", "moneyline"), ("total", "team_total")]
P("| market pair | games | mean within-game corr of tick-to-tick changes |")
P("|---|---|---|")
for a, b in pairs:
    cs = []
    for gid in set(k[0] for k in series):
        A = {k: v for k, v in series.items() if k[0] == gid and k[1] == a}
        B = {k: v for k, v in series.items() if k[0] == gid and k[1] == b}
        if not A or not B: continue
        da = diffs(list(A.values())[0]); db = diffs(list(B.values())[0])
        com = sorted(set(da) & set(db))
        if len(com) < 20: continue
        x = [da[t] for t in com]; y = [db[t] for t in com]
        mx, my = statistics.mean(x), statistics.mean(y)
        sx = math.sqrt(sum((v-mx)**2 for v in x)); sy = math.sqrt(sum((v-my)**2 for v in y))
        if sx <= 0 or sy <= 0: continue
        cs.append(sum((x[i]-mx)*(y[i]-my) for i in range(len(x)))/(sx*sy))
    if cs: P("| %s vs %s | %d | %+.3f |" % (a, b, len(cs), statistics.mean(cs)))
P("")
open(os.path.join(R, "outputs", "tables", "intra_game_correlation.md"), "w", encoding="utf-8").write("\n".join(OUT) + "\n")
print("\n[written]")
