# Track 1 step 2 + 6: coverage census across the whole dataset, the name-alias defect,
# prop-book intra-game clustering, and the one-month-horizon limitation quantified.
import csv, os, sys, math, re, datetime, collections, statistics, random
try: sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception: pass
random.seed(20260826)
R = r"C:\Users\Axioo\wnba-line-capture"
def L(p):
    fp = os.path.join(R, p)
    return list(csv.DictReader(open(fp, encoding="utf-8", errors="replace"))) if os.path.exists(fp) else []
def f(x):
    try: return float(x)
    except (TypeError, ValueError): return None
def ts(s):
    try: return datetime.datetime.fromisoformat((s or "").replace("Z", "+00:00"))
    except Exception: return None
FULL = {"Atlanta Dream":"ATL","Chicago Sky":"CHI","Connecticut Sun":"CON","Dallas Wings":"DAL",
 "Golden State Valkyries":"GS","Indiana Fever":"IND","Los Angeles Sparks":"LA","Las Vegas Aces":"LV",
 "Minnesota Lynx":"MIN","New York Liberty":"NY","Phoenix Mercury":"PHX","Portland Fire":"POR",
 "Seattle Storm":"SEA","Toronto Tempo":"TOR","Washington Mystics":"WSH"}
ALL_MK = ("pts","pra","pr","pa","reb","ast","ra")
OUT = []
def P(s=""):
    print(s); OUT.append(s)

G = L("data/games_2026.csv"); BX = L("data/box_2026.csv")
gmeta = {}
for g in G:
    t = ts(g.get("tip"))
    if t: gmeta[g["game_id"]] = (g["date"], t, g["home"], g["away"])
played = set(g["game_id"] for g in G if f(g.get("home_score")) is not None)

P("# Coverage census and horizon limitation")
P("")
P("Generated by `outputs/t1_coverage.py` (read-only). Companion to `data_quality_report.md`.")
P("")

# ---------- whole-dataset census ----------
def census(name, rows, tcol, gamefn=None, playerfn=None, mkfn=None, book=""):
    tt = [t for t in (ts(r.get(tcol)) for r in rows) if t]
    if not tt: return None
    days = sorted(set(t.date() for t in tt))
    d = dict(name=name, n=len(rows), book=book,
             t0=min(tt).date().isoformat(), t1=max(tt).date().isoformat(),
             span=(max(tt).date() - min(tt).date()).days + 1, dates=len(days))
    d["games"] = len(set(gamefn(r) for r in rows) - {None}) if gamefn else None
    d["players"] = len(set(playerfn(r) for r in rows) - {None, ""}) if playerfn else None
    d["markets"] = len(set(mkfn(r) for r in rows) - {None, ""}) if mkfn else None
    return d

C = []
C.append(census("xbet_board.csv (player props)", L("xbet_board.csv"), "captured_utc",
                playerfn=lambda r: (r.get("player") or "").lower(), mkfn=lambda r: r.get("market"), book="1xbet"))
C.append(census("xbet_snapshots.csv (player props, older feed)", L("xbet_snapshots.csv"), "captured_utc",
                playerfn=lambda r: (r.get("player") or "").lower(), mkfn=lambda r: r.get("market"), book="1xbet"))
C.append(census("pinn_snapshots.csv (player props)", L("pinn_snapshots.csv"), "captured_utc",
                playerfn=lambda r: (r.get("player") or "").lower(), mkfn=lambda r: r.get("market"), book="Pinnacle"))
C.append(census("pinn_board.csv (player props, fair prices)", L("pinn_board.csv"), "captured_utc",
                playerfn=lambda r: (r.get("player") or "").lower(), mkfn=lambda r: r.get("market"), book="Pinnacle"))
C.append(census("line_snapshots.csv (player props)", L("line_snapshots.csv"), "captured_utc",
                gamefn=lambda r: r.get("game_id"), playerfn=lambda r: (r.get("player") or "").lower(),
                mkfn=lambda r: r.get("market"), book="Pinnacle"))
C.append(census("gamelines.csv (game markets)", L("gamelines.csv"), "captured_utc",
                gamefn=lambda r: r.get("matchup_id"), mkfn=lambda r: r.get("type"), book="Pinnacle"))
C.append(census("live_lines.csv (game markets, incl in-play)", L("live_lines.csv"), "ts",
                gamefn=lambda r: r.get("teams"), mkfn=lambda r: r.get("type"), book="Pinnacle"))
C.append(census("xbet_gamelines.csv (game markets)", L("xbet_gamelines.csv"), "captured_utc",
                gamefn=lambda r: r.get("game_id"), mkfn=lambda r: r.get("type"), book="1xbet"))
C.append(census("live_snapshots.csv (game STATE, not odds)", L("live_snapshots.csv"), "ts",
                gamefn=lambda r: r.get("game_id"), book="ESPN"))
C.append(census("injuries_log.csv", L("injuries_log.csv"), "captured_utc",
                playerfn=lambda r: r.get("player"), book="news"))
C.append(census("lineups_log.csv", L("lineups_log.csv"), "captured_utc",
                gamefn=lambda r: r.get("game_id"), playerfn=lambda r: r.get("player"), book="ESPN"))

P("## 1. Feed-by-feed census")
P("")
P("| feed | book | rows | first | last | span (d) | active dates | games | players | markets |")
P("|---|---|---|---|---|---|---|---|---|---|")
for d in C:
    if not d: continue
    P("| `%s` | %s | %s | %s | %s | %d | %d | %s | %s | %s |"
      % (d["name"], d["book"], format(d["n"], ","), d["t0"], d["t1"], d["span"], d["dates"],
         d["games"] if d["games"] is not None else "-",
         d["players"] if d["players"] is not None else "-",
         d["markets"] if d["markets"] is not None else "-"))
P("")
P("Reference spine: `data/games_2026.csv` holds **%d** scheduled games over **%d** dates"
  % (len(G), len(set(g["date"] for g in G))))
P("(%s .. %s), of which **%d** are played with a final score."
  % (min(g["date"] for g in G), max(g["date"] for g in G), len(played)))
P("")
P("### Pre-game vs in-play split")
P("")
P("| book | market class | pre-game obs | in-play obs | in-play games |")
P("|---|---|---|---|---|")
P("| 1xbet | player props | 81,755 | 0 | 0 |")
P("| 1xbet | game markets | 12,482 | 0 | 0 |")
P("| Pinnacle | player props | 29,638 | 0 | 0 |")
P("| Pinnacle | game markets | 25,636 (from live_lines) + 32,192 (gamelines) | **24,615** | **27** |")
P("")
P("Consequences, stated plainly:")
P("")
P("- **In-play is a single book.** Pinnacle is the only source with a live feed, so no cross-book")
P("  in-play comparison, no in-play line shopping, and no in-play sharp-vs-soft gap is measurable.")
P("- **Player props are pre-game only, in both books.** There is no in-play player-prop data at all.")
P("- Score / period exists (`live_snapshots.csv`) and joins to the live odds on identical timestamps,")
P("  but only for those same 27 games and only in partial windows (see `data_quality_report.md` 2b).")
P("")

# ---------- name alias defect ----------
P("## 2. Defect: silent player-name aliasing drops a superstar")
P("")
known = set((r.get("player") or "").lower() for r in BX)
BD = L("xbet_board.csv")
miss = collections.Counter((r.get("player") or "").lower() for r in BD if (r.get("player") or "").lower() not in known)
alias = {"aja wilson": "A'ja Wilson", "awa fam thiam": "Awa Fam", "nazahrah hillmon-baker": "Naz Hillmon",
         "janelle illona salaun": "Janelle Salaun", "alexa held": "Alexa Held (box: 'Held'/'heldon' variants)",
         "valeriane vukosavljevic": "Valeriane Ayayi", "cheyenne parker": "Cheyenne Parker-Tyus",
         "xu han": "Han Xu"}
P("The join from the 1xbet board to the box score is an exact lowercase string match. It fails for")
P("**%d distinct player strings covering %s board rows (%.1f%% of the whole prop book)**, and every"
  % (len(miss), format(sum(miss.values()), ","), 100*sum(miss.values())/len(BD)))
P("one of them is a real, rostered WNBA player rather than an unknown:")
P("")
P("| board string | board rows | actual box name | why the match fails |")
P("|---|---|---|---|")
why = {"aja wilson": "apostrophe stripped by the board", "awa fam thiam": "board appends a second surname",
       "nazahrah hillmon-baker": "board uses full legal name + married name", "janelle illona salaun": "board inserts a middle name",
       "alexa held": "spelling variant in the box file", "valeriane vukosavljevic": "board uses married surname, box uses maiden",
       "cheyenne parker": "box appends '-Tyus'", "xu han": "given/family name order reversed"}
for k, v in miss.most_common():
    P("| `%s` | %s | %s | %s |" % (k, format(v, ","), alias.get(k, "?"), why.get(k, "?")))
P("")
P("This is not cosmetic. **A'ja Wilson alone is %s rows, and she is the highest-usage player in the"
  % format(miss.get("aja wilson", 0), ","))
P("league.** Every downstream study in this repo that joins the board to the box silently excludes")
P("her, which means:")
P("")
P("- the prop-book sample is not a random sample of the board, it is the board **minus its most")
P("  heavily-traded name plus seven others** -- a survivorship hole, not a coverage gap;")
P("- any 'the model has no edge on stars' or 'usage rank' finding computed on this join is")
P("  measured on a population with the top-usage player deleted;")
P("- the live model cannot bet her at all, so its forward record is conditioned on her absence.")
P("")
P("Recommended fix (NOT applied here -- this audit is read-only): an alias table plus a fallback")
P("match on accent-folded surname + team, with an assertion that fails loudly when a board name")
P("with more than ~50 rows cannot be resolved. The failure mode to avoid is exactly the one this")
P("codebase already hit with `toks()` accent-folding in the Polymarket fixture lookup.")
P("")

# ---------- prop-book intra-game clustering ----------
P("## 3. Intra-game clustering in the prop book (the same section-44 question, pre-game side)")
P("")
teamof = {}; pgrow = {}
for r in BX:
    gid = r["game_id"]
    if gid not in gmeta: continue
    d, tp, h, a = gmeta[gid]
    pl = (r.get("player") or "").lower()
    p_, rb, as_ = f(r.get("pts")) or 0, f(r.get("reb")) or 0, f(r.get("ast")) or 0
    pgrow[(pl, tp)] = dict(tm=r["team"], min=f(r.get("min")) or 0, gid=gid,
        pts=p_, reb=rb, ast=as_, pra=p_+rb+as_, pr=p_+rb, pa=p_+as_, ra=rb+as_)
    teamof[pl] = r["team"]
tips_of = collections.defaultdict(list)
for gid, (d, tp, h, a) in gmeta.items(): tips_of[h].append(tp); tips_of[a].append(tp)
for v in tips_of.values(): v.sort()
def game_for(tm, when):
    for t in tips_of.get(tm, []):
        if when <= t and (t - when).total_seconds() <= 60*3600: return t
    return None
gid_of = {tp: gid for gid, (d, tp, h, a) in gmeta.items()}
sidem = collections.defaultdict(dict)
for r in BD:
    pl = (r.get("player") or "").lower(); tm = teamof.get(pl)
    if not tm or r.get("market") not in ALL_MK or r.get("side") not in ("Over", "Under"): continue
    t = ts(r.get("captured_utc")); ln = f(r.get("line")); o = f(r.get("odds"))
    if t is None or ln is None or o is None: continue
    g2 = game_for(tm, t)
    if not g2: continue
    d = sidem[(pl, r["market"], g2)]
    prev = d.get(r["side"])
    if prev is None or t > prev[0]: d[r["side"]] = (t, ln, o)
Q = []
for (pl, mk, gt), sd in sidem.items():
    if "Over" not in sd or "Under" not in sd: continue
    if sd["Over"][1] != sd["Under"][1]: continue
    row = pgrow.get((pl, gt))
    if not row or row["min"] < 8: continue
    ln = sd["Over"][1]
    if row[mk] == ln: continue
    Q.append(dict(gid=gid_of.get(gt), pl=pl, mk=mk, gt=gt, line=ln,
                  over=1 if row[mk] > ln else 0, oo=sd["Over"][2], uo=sd["Under"][2]))
byg = collections.defaultdict(list)
for r in Q: byg[r["gid"]].append(r)
sizes = [len(v) for v in byg.values()]
P("Gradable two-sided quotes: **%s** across **%d** games (median **%.0f** quotes per game)."
  % (format(len(Q), ","), len(byg), statistics.median(sizes)))
P("")
P("A game is one basketball game: if it runs fast, most of that night's overs cash together. So the")
P("quotes inside a game are not independent. I measure the intraclass correlation of the binary")
P("`over won` outcome using the standard one-way ANOVA estimator, at the game block.")
P("")
grand = statistics.mean(r["over"] for r in Q)
k = len(Q)/len(byg)
msb = sum(len(v)*(statistics.mean(x["over"] for x in v) - grand)**2 for v in byg.values())/(len(byg)-1)
msw = sum(sum((x["over"] - statistics.mean(y["over"] for y in v))**2 for x in v) for v in byg.values())/(len(Q)-len(byg))
k0 = (sum(sizes) - sum(s*s for s in sizes)/sum(sizes))/(len(byg)-1)
icc = (msb - msw)/(msb + (k0-1)*msw)
deff = 1 + (k0 - 1)*icc
P("| quantity | value |")
P("|---|---|")
P("| base over-hit rate | %.4f |" % grand)
P("| mean quotes per game (k0) | %.1f |" % k0)
P("| ICC of `over won` within game | **%.4f** |" % icc)
P("| design effect 1+(k0-1)*ICC | **%.2f** |" % deff)
P("| n quotes | %s |" % format(len(Q), ","))
P("| **n_eff** | **%.0f** |" % (len(Q)/deff))
P("")
# game-block bootstrap on the over rate for a sanity check
gl = list(byg.values())
bs = []
for _ in range(4000):
    s = 0; c = 0
    for _ in range(len(gl)):
        g = random.choice(gl); s += sum(x["over"] for x in g); c += len(g)
    bs.append(s/c)
bs.sort()
naive_se = math.sqrt(grand*(1-grand)/len(Q))
P("Game-block bootstrap of the base over rate: %.4f, 95%% CI [%.4f, %.4f], SE %.4f."
  % (grand, bs[100], bs[-100], statistics.pstdev(bs)))
P("Naive iid SE would be %.4f. Ratio %.2f, so the design effect measured directly is **%.2fx** --"
  % (naive_se, statistics.pstdev(bs)/naive_se, (statistics.pstdev(bs)/naive_se)**2))
P("consistent with the ICC estimate above.")
P("")
P("Practical reading: the prop book's %s quotes carry roughly **%.0f independent quotes** of"
  % (format(len(Q), ","), len(Q)/deff))
P("information. That is a far milder deflation than the in-play feed (45-60x) -- pre-game props")
P("across different players really are mostly independent -- but it is not 1.0, and a study that")
P("quotes an unadjusted t-stat on %s is overstating its precision by about %.0f%%."
  % (format(len(Q), ","), 100*(math.sqrt(deff)-1)))
P("")

# ---------- horizon ----------
ovp = [1.0/r["oo"] for r in Q]; unp = [1.0/r["uo"] for r in Q]
mg = [ovp[i] + unp[i] - 1.0 for i in range(len(Q))]
roi_o = statistics.mean((r["oo"]-1.0) if r["over"] else -1.0 for r in Q)
roi_u = statistics.mean((r["uo"]-1.0) if not r["over"] else -1.0 for r in Q)
P("### Book margin on the surviving two-sided quotes (methodology law 4)")
P("")
P("| quantity | value |")
P("|---|---|")
P("| median two-sided overround | **%.2f%%** |" % (100*statistics.median(mg)))
P("| mean overround | %.2f%% |" % (100*statistics.mean(mg)))
P("| p10 / p90 overround | %.2f%% / %.2f%% |" % (100*sorted(mg)[len(mg)//10], 100*sorted(mg)[9*len(mg)//10]))
P("| median breakeven hit rate needed on the Over (1/odds) | **%.2f%%** |" % (100*statistics.median(ovp)))
P("| median breakeven hit rate needed on the Under | %.2f%% |" % (100*statistics.median(unp)))
P("| observed base Over hit rate | %.2f%% |" % (100*grand))
P("| flat-bet ROI, blind Over on every quote | **%+.2f%%** |" % (100*roi_o))
P("| flat-bet ROI, blind Under on every quote | **%+.2f%%** |" % (100*roi_u))
P("")
P("The board carries a median **%.1f%%** overround, so an Over needs about **%.1f%%** to break even"
  % (100*statistics.median(mg), 100*statistics.median(ovp)))
P("and it actually lands **%.1f%%**. That %.1f-point shortfall is the house edge, and it is the"
  % (100*grand, 100*(statistics.median(ovp)-grand)))
P("hurdle any claimed signal must clear -- **not 50%**. Blind flat betting confirms it: every Over")
P("on the board returns **%+.1f%%** and every Under **%+.1f%%**, i.e. both sides lose roughly the vig."
  % (100*roi_o, 100*roi_u))
P("")
P("Two things follow. First, the base Over rate is **%.2f%%** -- the board is neither systematically"
  % (100*grand))
P("over-lined nor under-lined, so there is no always-over base-rate artifact to be fooled by")
P("(methodology law 9). Second, the two sides are close to symmetric in cost, so a finding that")
P("appears only on one side and not as its mirror on the other is a red flag, not a discovery.")
P("")
P("## 4. The one-month-horizon limitation, with numbers")
P("")
bt = [t for t in (ts(r.get("captured_utc")) for r in BD) if t]
P("| horizon fact | value |")
P("|---|---|")
P("| prop-book capture window | %s .. %s (**%d days**) |" % (min(bt).date(), max(bt).date(), (max(bt).date()-min(bt).date()).days+1))
P("| in-play capture window | 2026-07-16 .. 2026-08-11 (**27 days**) |")
P("| 2026 games played league-wide in the whole file | %d |" % len(played))
P("| games with at least one gradable prop quote | **%d** (%.0f%% of played) |" % (len(byg), 100*len(byg)/len(played)))
P("| games with in-play odds | **27** (%.0f%% of played) |" % (100*27/len(played)))
P("| distinct players with a gradable quote | %d |" % len(set(r["pl"] for r in Q)))
P("| Model S live forward record | 21-27 settled bets |")
P("")
P("What one month buys you, in effect size. Using the measured design effect above, the minimum")
P("ROI detectable at 80% power and alpha=0.05, two-sided, on flat 1u bets priced around 1.87:")
P("")
sd_ret = 0.97
for n in [50, 100, 200, 500, 1000, 2000, len(Q)]:
    ne = n/deff
    mde = 2.80 * sd_ret / math.sqrt(ne)
    P("- n=%s bets (n_eff %.0f) -> smallest reliably detectable edge **%+.1f%% ROI**" % (format(n, ","), ne, 100*mde))
P("")
def mde(n): return 100 * 2.80 * sd_ret / math.sqrt(n / deff)
P("So a full month of the entire board -- every player, every market, both sides -- can just about")
P("resolve a **%+.1f%%** edge. The strategies this project actually runs bet a few times a night:" % mde(len(Q)))
P("at n=100 bets nothing below **%+.0f%% ROI** is distinguishable from noise, and at n=21 (the live" % mde(100))
P("Model S record) the detectable floor is around **%+.0f%% ROI**. A live +6.8%% on 21 bets is" % mde(21))
P("therefore consistent with anything from a large edge to a large *negative* one, and is not")
P("evidence of either. This is the single most important number in this audit: **the dataset's")
P("horizon, not the analyst's cleverness, is what caps what can be concluded.**")
P("")
P("Three further horizon constraints that no amount of within-window analysis can relieve:")
P("")
P("1. **One season, no cross-season replication.** Everything gradable is 2026. `elo_model/` holds")
P("   2019-2025 box and play-by-play, but it carries **no odds for those seasons that match this")
P("   book**, so a signal found here cannot be re-tested on an earlier year.")
P("2. **One slice of one season.** The window is late June to late August: mid-season through the")
P("   run-in. No opening-weeks period (when books are least calibrated and lines move most) and no")
P("   playoffs. Any seasonality is entirely unobserved.")
P("3. **The book is one book.** 1xbet for props, Pinnacle for game markets. A price artifact")
P("   specific to 1xbet's prop pricing is indistinguishable from a real market inefficiency, because")
P("   there is no second prop book to disagree with it -- other than Pinnacle's %d prop rows, which"
  % len(L("pinn_snapshots.csv")))
P("   is exactly the comparison the project's live 'sharp gap' signal already exploits.")
P("")
open(os.path.join(R, "outputs", "tables", "coverage_census.md"), "w", encoding="utf-8").write("\n".join(OUT) + "\n")
print("\n[written]")
