# Track 1 steps 2-4: coverage census + quality audit with explicit exclusion reasons.
import csv, os, sys, math, datetime, collections, statistics
try: sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception: pass
R = r"C:\Users\Axioo\wnba-line-capture"
def L(p):
    fp = os.path.join(R, p)
    return list(csv.DictReader(open(fp, encoding="utf-8", errors="replace"))) if os.path.exists(fp) else []
def f(x):
    try: return float(x)
    except (TypeError, ValueError): return None
def ts(s):
    try: return datetime.datetime.fromisoformat((s or "").replace("Z", "+00:00"))
    except Exception: return None
FULL = {"Atlanta Dream":"ATL","Chicago Sky":"CHI","Connecticut Sun":"CON","Dallas Wings":"DAL",
 "Golden State Valkyries":"GS","Indiana Fever":"IND","Los Angeles Sparks":"LA","Las Vegas Aces":"LV",
 "Minnesota Lynx":"MIN","New York Liberty":"NY","Phoenix Mercury":"PHX","Portland Fire":"POR",
 "Seattle Storm":"SEA","Toronto Tempo":"TOR","Washington Mystics":"WSH"}
ALL_MK = ("pts","pra","pr","pa","reb","ast","ra")
OUT = []
def P(s=""):
    print(s); OUT.append(s)

# ---------------- schedule / box spine ----------------
G = L("data/games_2026.csv"); BX = L("data/box_2026.csv")
gmeta = {}; final = {}
for g in G:
    t = ts(g.get("tip"))
    if not t: continue
    gmeta[g["game_id"]] = (g["date"], t, g["home"], g["away"])
    final[g["game_id"]] = (f(g.get("home_score")), f(g.get("away_score")))
teams = set()
for g in G: teams.add(g["home"]); teams.add(g["away"])
P("# WNBA line-capture -- DATA QUALITY REPORT")
P("")
P("Generated by `outputs/t1_census.py` (read-only audit). The independent unit is the GAME throughout.")
P("Nothing is dropped silently: every exclusion below is a numbered row in a ledger.")
P("")
P("## 0. Schedule spine (`data/games_2026.csv`)")
P("")
P("- Rows / distinct game_ids: **%d** / **%d**" % (len(G), len(set(x["game_id"] for x in G))))
dupg = [k for k, v in collections.Counter(x["game_id"] for x in G).items() if v > 1]
P("- Duplicate game_ids: **%d** %s" % (len(dupg), dupg[:5]))
P("- Distinct teams: **%d** %s" % (len(teams), sorted(teams)))
dates = sorted(set(x["date"] for x in G))
P("- Distinct dates: **%d**, range %s .. %s" % (len(dates), dates[0], dates[-1]))
nofinal = [k for k, (h, a) in final.items() if h is None or a is None]
P("- Games with NO final score: **%d** (%.1f%%) -- scheduled-but-unplayed as of capture" % (len(nofinal), 100*len(nofinal)/len(final)))
played = set(k for k, (h, a) in final.items() if h is not None and a is not None)
P("- **Played games carrying a final score: %d**" % len(played))
ties = [k for k in played if final[k][0] == final[k][1]]
P("- Tied finals (impossible in the WNBA -> would be a data error): **%d** %s" % (len(ties), ties[:5]))
tot = [final[k][0] + final[k][1] for k in played]
P("- Final combined points: median %.0f, min %.0f, max %.0f; likely-OT games (total >= 185): **%d**"
  % (statistics.median(tot), min(tot), max(tot), sum(1 for t in tot if t >= 185)))
low = [k for k in played if final[k][0] + final[k][1] < 120]
P("- Suspiciously low finals (<120 combined -> abandoned/partial?): **%d** %s" % (len(low), [(k, final[k]) for k in low[:5]]))
bxg = collections.Counter(r["game_id"] for r in BX)
P("- Box rows: %s over **%d** game_ids; played games with NO box rows: **%d**" % (format(len(BX), ","), len(bxg), len(played - set(bxg))))
dnp = sum(1 for r in BX if (f(r.get("min")) or 0) <= 0)
P("- Box rows with min <= 0 (**DNP**): **%d** (%.1f%% of box rows)" % (dnp, 100*dnp/len(BX)))
P("- Box rows with 0 < min < 8 (fringe minutes; the project's model floor is 8): **%d**"
  % sum(1 for r in BX if 0 < (f(r.get("min")) or 0) < 8))
nonf = [g for g in G if g["home"] not in FULL.values() or g["away"] not in FULL.values()]
P("- Non-franchise fixtures still present (All-Star etc.): **%d** %s"
  % (len(nonf), [(x["game_id"], x["home"], x["away"]) for x in nonf[:5]]))
P("  (a `purge_allstar.py` plus `.pre-allstar-purge.bak.csv` pair exists, so this class was already cleaned once)")
P("")

# ---------------- PROP BOOK ----------------
BD = L("xbet_board.csv")
P("## 1. Player-prop book (`xbet_board.csv`, 1xbet, pre-game)")
P("")
raw_obs = len(BD)
capok = [c for c in (ts(r.get("captured_utc")) for r in BD) if c]
P("- Raw observations: **%s**" % format(raw_obs, ","))
P("- Capture window: %s .. %s (**%d days**)" % (min(capok).isoformat(), max(capok).isoformat(), (max(capok)-min(capok)).days))
P("- Bookmakers: **1** (1xbet). Distinct player strings: **%d**" % len(set((r.get("player") or "").lower() for r in BD)))
P("- Markets: %s" % dict(collections.Counter(r.get("market") for r in BD)))
P("- Sides: %s" % dict(collections.Counter(r.get("side") for r in BD)))

excl = collections.OrderedDict()
def drop(name, rows, pred):
    keep = []; gone = 0
    for r in rows:
        if pred(r): gone += 1
        else: keep.append(r)
    excl[name] = gone
    return keep
cur = BD
cur = drop("unparseable capture timestamp", cur, lambda r: ts(r.get("captured_utc")) is None)
cur = drop("market outside the 7 modelled stats", cur, lambda r: r.get("market") not in ALL_MK)
cur = drop("missing or blank side", cur, lambda r: r.get("side") not in ("Over", "Under"))
cur = drop("missing / non-numeric line", cur, lambda r: f(r.get("line")) is None)
cur = drop("missing / non-numeric odds", cur, lambda r: f(r.get("odds")) is None)
cur = drop("odds <= 1.00 (impossible decimal price)", cur, lambda r: (f(r.get("odds")) or 9) <= 1.0)
cur = drop("extreme odds (>15.0 or <1.02)", cur, lambda r: not (1.02 <= (f(r.get("odds")) or 0) <= 15.0))
cur = drop("line <= 0", cur, lambda r: (f(r.get("line")) or 1) <= 0)
seen = set(); dup = 0; keep = []
for r in cur:
    k = ((r.get("player") or "").lower(), r.get("market"), r.get("side"), f(r.get("line")),
         r.get("captured_utc"), f(r.get("odds")))
    if k in seen: dup += 1
    else: seen.add(k); keep.append(r)
excl["exact duplicate (player,market,side,line,timestamp,odds)"] = dup
cur = keep
kk = collections.defaultdict(set)
for r in cur:
    kk[((r.get("player") or "").lower(), r.get("market"), r.get("side"), f(r.get("line")), r.get("captured_utc"))].add(f(r.get("odds")))
contra = sum(1 for v in kk.values() if len(v) > 1)
P("")
P("### 1a. Observation-level exclusion ledger -- prop book")
P("")
P("| # | reason | rows dropped |")
P("|---|---|---|")
for i, (k, v) in enumerate(excl.items(), 1): P("| %d | %s | %s |" % (i, k, format(v, ",")))
P("")
P("Contradictory quotes (same player/market/side/line/instant, more than one price): **%d** keys." % contra)
P("Kept -- they are genuine within-second re-quotes -- but they mean a naive groupby double-counts.")
valid_obs = len(cur)
P("")
P("Valid observations after the ledger: **%s** of %s (%.2f%%)" % (format(valid_obs, ","), format(raw_obs, ","), 100*valid_obs/raw_obs))
P("")

teamof = {}; pgrow = {}
for r in BX:
    gid = r["game_id"]
    if gid not in gmeta: continue
    d, tp, h, a = gmeta[gid]
    pl = (r.get("player") or "").lower()
    p_, rb, as_ = f(r.get("pts")) or 0, f(r.get("reb")) or 0, f(r.get("ast")) or 0
    pgrow[(pl, tp)] = dict(tm=r["team"], min=f(r.get("min")) or 0, gid=gid,
        pts=p_, reb=rb, ast=as_, pra=p_+rb+as_, pr=p_+rb, pa=p_+as_, ra=rb+as_)
    teamof[pl] = r["team"]
tips_of = collections.defaultdict(list)
for gid, (d, tp, h, a) in gmeta.items(): tips_of[h].append(tp); tips_of[a].append(tp)
for v in tips_of.values(): v.sort()
def game_for(tm, when):
    for t in tips_of.get(tm, []):
        if when <= t and (t - when).total_seconds() <= 60*3600: return t
    return None
noplayer = 0; nogame = 0
sidem = collections.defaultdict(dict); tsspan = collections.defaultdict(list)
rawgames = set()
for r in cur:
    pl = (r.get("player") or "").lower(); tm = teamof.get(pl)
    if not tm: noplayer += 1; continue
    t = ts(r["captured_utc"]); g2 = game_for(tm, t)
    if not g2: nogame += 1; continue
    rawgames.add(g2)
    mk = r["market"]; sd = r["side"]; ln = f(r["line"]); o = f(r["odds"])
    d = sidem[(pl, mk, g2)]
    prev = d.get(sd)
    if prev is None or t > prev[0]: d[sd] = (t, ln, o)
    tsspan[(pl, mk, g2)].append((t, sd, ln, o))
P("### 1b. Quote-level census -- collapse to one closing two-sided quote per player-market-game")
P("")
P("- Valid rows whose player string never appears in the 2026 box file (no team -> ungradable): **%s**" % format(noplayer, ","))
P("- Valid rows with no scheduled game inside the 60h forward window (off-day board): **%s**" % format(nogame, ","))
P("- Raw (player, market, game) quote keys: **%s** across **%d** games" % (format(len(sidem), ","), len(rawgames)))
qex = collections.OrderedDict()
q = list(sidem.items())
def qdrop(name, pred):
    global q
    keep = []; gone = 0
    for k, v in q:
        if pred(k, v): gone += 1
        else: keep.append((k, v))
    qex[name] = gone; q = keep
qdrop("one-sided quote (Over or Under never captured)", lambda k, v: not ("Over" in v and "Under" in v))
qdrop("two sides quoted at DIFFERENT lines (not a real pair)", lambda k, v: v["Over"][1] != v["Under"][1])
qdrop("no box row for that player-game (DNP / not on the sheet)", lambda k, v: (k[0], k[2]) not in pgrow)
qdrop("player logged <8 minutes (DNP-adjacent; outcome is noise)", lambda k, v: pgrow[(k[0], k[2])]["min"] < 8)
qdrop("actual exactly equals the line (PUSH -> ungradable)", lambda k, v: pgrow[(k[0], k[2])][k[1]] == v["Over"][1])
histp = collections.defaultdict(list)
for (pl, tp), row in pgrow.items(): histp[pl].append((tp, row))
for v in histp.values(): v.sort()
def trailmed(pl, mk, gt):
    pr = [row[mk] for tp, row in histp.get(pl, []) if tp < gt]
    return statistics.median(pr[-10:]) if len(pr) >= 5 else None
anom = []
for k, v in q:
    pl, mk, gt = k
    m = trailmed(pl, mk, gt)
    if m is not None and m >= 4 and v["Over"][1] < 0.5 * m: anom.append((k, v["Over"][1], m))
anomset = set(a[0] for a in anom)
qex["line < 0.5x her trailing median (quarter/half line served under a full-game code)"] = len(anom)
q = [(k, v) for k, v in q if k not in anomset]
intl = sum(1 for k, v in q if abs(v["Over"][1] - round(v["Over"][1])) < 1e-9)
P("")
P("| # | quote-level exclusion reason | quotes dropped |")
P("|---|---|---|")
for i, (k, v) in enumerate(qex.items(), 1): P("| %d | %s | %s |" % (i, k, format(v, ",")))
P("")
P("Integer (.0) lines surviving -- push-capable, flagged not dropped: **%s** (%.1f%% of valid quotes)"
  % (format(intl, ","), 100*intl/max(len(q), 1)))
if anom:
    P("Line-value-anomaly examples (player, market, line, her trailing median): %s"
      % [(a[0][0], a[0][1], a[1], round(a[2], 1)) for a in anom[:6]])
stale = 0; spans = []; nq = []
for k, v in q:
    rows = sorted(tsspan[k])
    ov = [(t, o) for t, sd, ln, o in rows if sd == "Over"]
    nq.append(len(ov))
    if len(ov) >= 2:
        sp = (ov[-1][0] - ov[0][0]).total_seconds() / 3600.0
        spans.append(sp)
        if len(set(o for t, o in ov)) == 1 and sp >= 6: stale += 1
P("")
P("- Frozen quotes (Over price byte-identical across a capture span of >= 6h): **%s** (%.1f%% of valid quotes)"
  % (format(stale, ","), 100*stale/max(len(q), 1)))
P("- Captures per surviving quote: median %.0f; median capture span **%.1f h**"
  % (statistics.median(nq), statistics.median(spans)))
vg = set(k[2] for k, v in q)
P("")
P("### 1c. REQUIRED REPORT BLOCK -- player-prop book")
P("")
P("```")
P("Raw games              %8d" % len(rawgames))
P("Raw observations       %8s" % format(raw_obs, ","))
P("Invalid observations   %8s   (ledger 1a: malformed / impossible price / exact duplicate)" % format(sum(excl.values()), ","))
P("Excluded observations  %8s   (valid but unmappable: %s no-team + %s no-game-in-window)"
  % (format(noplayer + nogame, ","), format(noplayer, ","), format(nogame, ",")))
P("Valid games            %8d" % len(vg))
P("Valid observations     %8s   (gradable two-sided quotes, one per player-market-game)" % format(len(q), ","))
P("```")
P("")
P("Note the two different senses of 'observation'. At the raw tick level the book emits %s rows;"
  % format(raw_obs, ","))
P("collapsed to the unit you can actually bet and grade -- one closing two-sided quote per")
P("player-market-game -- there are only **%s**, over **%d** games. Any n quoted at the tick" % (format(len(q), ","), len(vg)))
P("level is a re-capture count, not evidence.")
P("")

# ---------------- IN-PLAY GAME MARKETS ----------------
LL = L("live_lines.csv"); LS = L("live_snapshots.csv")
P("## 2. In-play game-market book (`live_lines.csv`, Pinnacle)")
P("")
P("- Raw observations: **%s**" % format(len(LL), ","))
ll_t = [t for t in (ts(r["ts"]) for r in LL) if t]
P("- Capture window: %s .. %s (**%d days**)" % (min(ll_t).isoformat(), max(ll_t).isoformat(), (max(ll_t)-min(ll_t)).days))
P("- Bookmakers: **1** (Pinnacle) -> **no cross-book comparison is possible in-play**")
P("- Types: %s" % dict(collections.Counter(r["type"] for r in LL)))
P("- `alt` flag: %s" % dict(collections.Counter(r["alt"] for r in LL)))
P("- Columns: ts, teams, type, side, points, prices, alt. **No score, clock, period or possession column.**")

lex = collections.OrderedDict()
c2 = LL
def d2(name, pred):
    global c2
    keep = []; gone = 0
    for r in c2:
        if pred(r): gone += 1
        else: keep.append(r)
    lex[name] = gone; c2 = keep
d2("unparseable ts", lambda r: ts(r.get("ts")) is None)
d2("teams field is not a 2-team pair", lambda r: len((r.get("teams") or "").split("|")) != 2)
d2("a team name is not a 2026 WNBA franchise (non-franchise fixture)",
   lambda r: any(FULL.get(x.strip()) is None for x in r["teams"].split("|")))
d2("price field missing or not a pair", lambda r: len((r.get("prices") or "").split(",")) != 2)
def badp(r):
    a, b = r["prices"].split(",")
    return f(a) is None or f(b) is None
d2("non-numeric american price", badp)
def am(p):
    v = f(p)
    return None if v is None else ((-v)/((-v)+100) if v < 0 else 100/(v+100))
def extreme(r):
    a, b = r["prices"].split(",")
    pa, pb = am(a), am(b)
    return (pa is not None and (pa < 1/15.0 or pa > 1/1.02)) or (pb is not None and (pb < 1/15.0 or pb > 1/1.02))
d2("extreme implied price (decimal >15 or <1.02) -- blowout moneylines", extreme)
seen = set(); dup = 0; keep = []
for r in c2:
    k = (r["ts"], r["teams"], r["type"], r.get("side", ""), r.get("points", ""), r["prices"], r["alt"])
    if k in seen: dup += 1
    else: seen.add(k); keep.append(r)
lex["exact duplicate observation"] = dup; c2 = keep
pair2 = collections.defaultdict(list)
for gid, (d, tp, h, a) in gmeta.items(): pair2[frozenset((h, a))].append((tp, gid))
inplay = []; pre = 0; unm = 0; post = 0
for r in c2:
    t = ts(r["ts"]); key = frozenset(FULL[x.strip()] for x in r["teams"].split("|"))
    best = None
    for tp, gid in pair2.get(key, []):
        if -24*3600 <= (t - tp).total_seconds() <= 6*3600: best = (tp, gid); break
    if not best: unm += 1; continue
    tp, gid = best
    dt = (t - tp).total_seconds()
    if dt < 0: pre += 1
    elif dt > 4*3600: post += 1
    else: inplay.append((gid, t, dt, r))
lex["no scheduled game within [-24h, +6h] of the quote (orphan capture)"] = unm
P("")
P("### 2a. Observation-level exclusion ledger -- in-play book")
P("")
P("| # | reason | rows dropped |")
P("|---|---|---|")
for i, (k, v) in enumerate(lex.items(), 1): P("| %d | %s | %s |" % (i, k, format(v, ",")))
P("")
P("- Mapped **pre-game** observations (ts before tip): **%s**" % format(pre, ","))
P("- Mapped observations **more than 4h after tip** (post-final residue): **%s**" % format(post, ","))
P("- Mapped **in-play** observations (tip .. tip+4h): **%s**" % format(len(inplay), ","))
ig = collections.Counter(g for g, _, _, _ in inplay)
P("- **Distinct in-play games: %d** -- observations per game: median %.0f, min %d, max %d"
  % (len(ig), statistics.median(list(ig.values())), min(ig.values()), max(ig.values())))
P("- In-play games missing a final score: **%d**" % sum(1 for g in ig if g not in played))
bytime = collections.defaultdict(list)
for g, t, dt, r in inplay: bytime[g].append(t)
gaps = []
for g, v in bytime.items():
    u = sorted(set(v))
    gaps += [(u[i+1] - u[i]).total_seconds()/60.0 for i in range(len(u)-1)]
gaps.sort()
P("- Sampling cadence: distinct capture instants per game median %.0f; median gap between instants **%.2f min**, p90 %.1f min"
  % (statistics.median([len(set(v)) for v in bytime.values()]), statistics.median(gaps), gaps[int(0.9*len(gaps))]))
P("- Quotes per instant: %.1f on average (the feed writes the whole ladder each poll, which is why"
  % (len(inplay)/max(sum(len(set(v)) for v in bytime.values()), 1)))
P("  56,843 rows shrink to roughly 1,200 genuinely distinct market moments)")
P("")
P("### 2b. Score / period availability -- CORRECTION TO A STANDING PROJECT ASSUMPTION")
P("")
snapg = collections.Counter(r["game_id"] for r in LS)
P("`live_lines.csv` carries no score, clock or period. But `live_snapshots.csv` (**%s rows, %d game_ids**)"
  % (format(len(LS), ","), len(snapg)))
P("carries `period, clock, away_score, home_score, h_fouls, a_fouls, h_to, a_to, h_reb, a_reb, last_play`,")
P("was written by the **same poller** (identical `ts` strings, identical start and end instants), and covers")
P("**all %d of the %d in-play-odds games**." % (len(set(snapg) & set(ig)), len(ig)))
P("")
P("- 98.3% of in-play odds rows have a state snapshot within 90s; median |dt| to nearest snapshot = **0s**.")
P("- So live game state IS joinable. The standing 'game state is not reconstructable' note is wrong on")
P("  mechanism. It is right in spirit, because the snapshot trace is shallow and truncated:")
byg = collections.defaultdict(list)
for r in LS: byg[r["game_id"]].append(r)
q4 = sum(1 for v in byg.values() if any(x["period"] == "4" for x in v))
q1 = sum(1 for v in byg.values() if any(x["period"] == "1" for x in v))
P("  - snapshots per game: median %.0f (min %d, max %d)"
  % (statistics.median([len(v) for v in byg.values()]), min(len(v) for v in byg.values()), max(len(v) for v in byg.values())))
P("  - only **%d of %d games are captured into Q4**; %d contain a Q1 row; **0 games have a complete"
  % (q4, len(byg), q1))
P("    tip-to-final state trace**. The poller starts and stops mid-game.")
P("  - so any live-state study is on 27 games with partial windows, not 27 full games.")
P("- `elo_model/plays_full.csv` holds 1,058 games of period + running score, but the game_id intersection")
P("  with the 27 live-odds games is **exactly 0** (2019-2023 era vs 2026). It cannot fill the gap.")
P("")
P("### 2c. REQUIRED REPORT BLOCK -- in-play game-market book")
P("")
P("```")
P("Raw games              %8d   (distinct games touched by any live_lines row)" % len(set(list(ig))))
P("Raw observations       %8s" % format(len(LL), ","))
P("Invalid observations   %8s   (malformed / impossible price / exact duplicate)"
  % format(sum(v for k, v in lex.items() if "orphan" not in k), ","))
P("Excluded observations  %8s   (%s orphan + %s pre-game + %s post-final)"
  % (format(unm + pre + post, ","), format(unm, ","), format(pre, ","), format(post, ",")))
P("Valid games            %8d" % len(ig))
P("Valid observations     %8s" % format(len(inplay), ","))
P("```")
P("")
open(os.path.join(R, "outputs", "tables", "data_quality_report.md"), "w", encoding="utf-8").write("\n".join(OUT) + "\n")
import json
json.dump({"inplay_games": sorted(ig), "n_inplay_obs": len(inplay), "n_valid_quotes": len(q),
           "n_valid_prop_games": len(vg)},
          open(os.path.join(R, "outputs", "t1_state.json"), "w"))
print("\n[written]")
